language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
script:
 - python -m unittest discover Warmup-1
 - python -m unittest discover Warmup-2
 - python -m unittest discover List-1
 - python -m unittest discover List-2
 - python -m unittest discover String-1
 - python -m unittest discover String-2
 - python -m unittest discover Logic-1
 - python -m unittest discover Logic-2